/**
 * catechismData.ts — Westminster Shorter Catechism + Heidelberg Q&A
 * Built-in offline dataset — no API required.
 */

export interface CatechismQuestion {
  id: string;
  number: number;
  question: string;
  answer: string;
  proofTexts: string[];
  category: string;
}

export interface Catechism {
  id: string;
  name: string;
  shortName: string;
  year: string;
  tradition: string;
  description: string;
  questions: CatechismQuestion[];
}

export const WESTMINSTER_SHORTER: Catechism = {
  id: 'wsc',
  name: 'Westminster Shorter Catechism',
  shortName: 'WSC',
  year: '1647',
  tradition: 'Reformed / Presbyterian',
  description: 'Composed by the Westminster Assembly, this 107-question catechism remains one of the most precise summaries of Reformed doctrine and Christian living.',
  questions: [
    { id: 'wsc-1', number: 1, category: 'Purpose', question: "What is the chief end of man?", answer: "Man's chief end is to glorify God, and to enjoy him forever.", proofTexts: ['1 Corinthians 10:31', 'Psalm 73:25-28'] },
    { id: 'wsc-2', number: 2, category: 'Scripture', question: "What rule has God given to direct us how we may glorify and enjoy him?", answer: "The Word of God, which is contained in the Scriptures of the Old and New Testaments, is the only rule to direct us how we may glorify and enjoy him.", proofTexts: ['2 Timothy 3:16', 'Ephesians 2:20'] },
    { id: 'wsc-3', number: 3, category: 'Scripture', question: "What do the Scriptures principally teach?", answer: "The Scriptures principally teach what man is to believe concerning God, and what duty God requires of man.", proofTexts: ['2 Timothy 1:13', 'Deuteronomy 10:12-13'] },
    { id: 'wsc-4', number: 4, category: 'God', question: "What is God?", answer: "God is a Spirit, infinite, eternal, and unchangeable in his being, wisdom, power, holiness, justice, goodness, and truth.", proofTexts: ['John 4:24', 'Psalm 90:2', 'James 1:17', 'Revelation 4:8'] },
    { id: 'wsc-5', number: 5, category: 'God', question: "Are there more Gods than one?", answer: "There is but one only, the living and true God.", proofTexts: ['Deuteronomy 6:4', '1 Corinthians 8:4', 'Jeremiah 10:10'] },
    { id: 'wsc-6', number: 6, category: 'Trinity', question: "How many persons are there in the Godhead?", answer: "There are three persons in the Godhead: the Father, the Son, and the Holy Ghost; and these three are one God, the same in substance, equal in power and glory.", proofTexts: ['Matthew 28:19', '2 Corinthians 13:14', 'John 10:30'] },
    { id: 'wsc-7', number: 7, category: 'Decrees', question: "What are the decrees of God?", answer: "The decrees of God are his eternal purpose, according to the counsel of his will, whereby, for his own glory, he has foreordained whatsoever comes to pass.", proofTexts: ['Ephesians 1:4', 'Romans 9:22-23', 'Isaiah 46:10'] },
    { id: 'wsc-8', number: 8, category: 'Creation', question: "How does God execute his decrees?", answer: "God executes his decrees in the works of creation and providence.", proofTexts: ['Revelation 4:11', 'Daniel 4:35'] },
    { id: 'wsc-9', number: 9, category: 'Creation', question: "What is the work of creation?", answer: "The work of creation is God's making all things of nothing, by the word of his power, in the space of six days, and all very good.", proofTexts: ['Genesis 1:1', 'Hebrews 11:3', 'Colossians 1:16'] },
    { id: 'wsc-10', number: 10, category: 'Creation', question: "How did God create man?", answer: "God created man male and female, after his own image, in knowledge, righteousness, and holiness, with dominion over the creatures.", proofTexts: ['Genesis 1:27', 'Colossians 3:10', 'Ephesians 4:24'] },
    { id: 'wsc-11', number: 11, category: 'Providence', question: "What are God's works of providence?", answer: "God's works of providence are his most holy, wise, and powerful preserving and governing all his creatures, and all their actions.", proofTexts: ['Psalm 145:17', 'Isaiah 28:29', 'Hebrews 1:3'] },
    { id: 'wsc-12', number: 12, category: 'Sin', question: "What special act of providence did God exercise toward man in the estate wherein he was created?", answer: "When God had created man, he entered into a covenant of life with him, upon condition of perfect obedience; forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death.", proofTexts: ['Galatians 3:12', 'Genesis 2:17'] },
    { id: 'wsc-13', number: 13, category: 'Sin', question: "Did our first parents continue in the estate wherein they were created?", answer: "Our first parents, being left to the freedom of their own will, fell from the estate wherein they were created, by sinning against God.", proofTexts: ['Genesis 3:6-8', 'Ecclesiastes 7:29'] },
    { id: 'wsc-14', number: 14, category: 'Sin', question: "What is sin?", answer: "Sin is any want of conformity unto, or transgression of, the law of God.", proofTexts: ['1 John 3:4', 'James 4:17'] },
    { id: 'wsc-15', number: 15, category: 'Sin', question: "What was the sin whereby our first parents fell from the estate wherein they were created?", answer: "The sin whereby our first parents fell from the estate wherein they were created was their eating the forbidden fruit.", proofTexts: ['Genesis 3:6', 'Romans 5:12'] },
    { id: 'wsc-16', number: 16, category: 'Sin', question: "Did all mankind fall in Adam's first transgression?", answer: "The covenant being made with Adam, not only for himself, but for his posterity; all mankind, descending from him by ordinary generation, sinned in him, and fell with him in his first transgression.", proofTexts: ['Romans 5:12', '1 Corinthians 15:22'] },
    { id: 'wsc-17', number: 17, category: 'Sin', question: "Into what estate did the fall bring mankind?", answer: "The fall brought mankind into an estate of sin and misery.", proofTexts: ['Romans 5:18', 'Galatians 3:10'] },
    { id: 'wsc-18', number: 18, category: 'Sin', question: "Wherein consists the sinfulness of that estate whereinto man fell?", answer: "The sinfulness of that estate whereinto man fell consists in the guilt of Adam's first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called original sin; together with all actual transgressions which proceed from it.", proofTexts: ['Romans 5:19', 'Romans 3:10-19', 'Ephesians 2:1-3'] },
    { id: 'wsc-19', number: 19, category: 'Sin', question: "What is the misery of that estate whereinto man fell?", answer: "All mankind by their fall lost communion with God, are under his wrath and curse, and so made liable to all the miseries of this life, to death itself, and to the pains of hell forever.", proofTexts: ['Genesis 3:8', 'Ephesians 2:3', 'Galatians 3:10', 'Romans 6:23'] },
    { id: 'wsc-20', number: 20, category: 'Redemption', question: "Did God leave all mankind to perish in the estate of sin and misery?", answer: "God, having out of his mere good pleasure, from all eternity, elected some to everlasting life, did enter into a covenant of grace, to deliver them out of the estate of sin and misery, and to bring them into an estate of salvation by a Redeemer.", proofTexts: ['Ephesians 1:4', 'Romans 3:20-22', 'Galatians 3:21-22'] },
    { id: 'wsc-21', number: 21, category: 'Christ', question: "Who is the Redeemer of God's elect?", answer: "The only Redeemer of God's elect is the Lord Jesus Christ, who, being the eternal Son of God, became man, and so was, and continueth to be, God and man in two distinct natures, and one person, forever.", proofTexts: ['1 Timothy 2:5', 'John 1:14', 'Hebrews 7:24-25'] },
    { id: 'wsc-22', number: 22, category: 'Christ', question: "How did Christ, being the Son of God, become man?", answer: "Christ, the Son of God, became man by taking to himself a true body and a reasonable soul, being conceived by the power of the Holy Ghost in the womb of the virgin Mary, and born of her, yet without sin.", proofTexts: ['Hebrews 2:14', 'Matthew 1:20-23', 'Hebrews 4:15'] },
    { id: 'wsc-23', number: 23, category: 'Christ', question: "What offices does Christ execute as our Redeemer?", answer: "Christ, as our Redeemer, executes the offices of a prophet, of a priest, and of a king, both in his estate of humiliation and exaltation.", proofTexts: ['Acts 3:22', 'Hebrews 5:6', 'Psalm 2:6'] },
    { id: 'wsc-24', number: 24, category: 'Christ', question: "How does Christ execute the office of a prophet?", answer: "Christ executes the office of a prophet, in revealing to us, by his Word and Spirit, the will of God for our salvation.", proofTexts: ['John 1:18', 'John 15:15', '1 Peter 1:10-12'] },
    { id: 'wsc-25', number: 25, category: 'Christ', question: "How does Christ execute the office of a priest?", answer: "Christ executes the office of a priest, in his once offering up of himself a sacrifice to satisfy divine justice, and reconcile us to God; and in making continual intercession for us.", proofTexts: ['Hebrews 9:14', 'Hebrews 2:17', 'Hebrews 7:24-25'] },
    { id: 'wsc-26', number: 26, category: 'Christ', question: "How does Christ execute the office of a king?", answer: "Christ executes the office of a king, in subduing us to himself, in ruling and defending us, and in restraining and conquering all his and our enemies.", proofTexts: ['Psalm 110:3', 'Isaiah 33:22', '1 Corinthians 15:25'] },
    { id: 'wsc-27', number: 27, category: 'Salvation', question: "Wherein did Christ's humiliation consist?", answer: "Christ's humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time.", proofTexts: ['Luke 2:7', 'Galatians 4:4', 'Hebrews 12:2-3'] },
    { id: 'wsc-28', number: 28, category: 'Salvation', question: "Wherein consisteth Christ's exaltation?", answer: "Christ's exaltation consisteth in his rising again from the dead on the third day, in ascending up into heaven, in sitting at the right hand of God the Father, and in coming to judge the world at the last day.", proofTexts: ['1 Corinthians 15:4', 'Acts 1:11', 'Ephesians 1:20', 'Acts 17:31'] },
    { id: 'wsc-29', number: 29, category: 'Salvation', question: "How are we made partakers of the redemption purchased by Christ?", answer: "We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit.", proofTexts: ['John 1:11-12', 'John 3:5-6', 'Titus 3:5-6'] },
    { id: 'wsc-30', number: 30, category: 'Salvation', question: "How does the Spirit apply to us the redemption purchased by Christ?", answer: "The Spirit applies to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ in our effectual calling.", proofTexts: ['Ephesians 1:13-14', 'Ephesians 2:8', '1 Corinthians 1:9'] },
    { id: 'wsc-31', number: 31, category: 'Salvation', question: "What is effectual calling?", answer: "Effectual calling is the work of God's Spirit, whereby, convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he does persuade and enable us to embrace Jesus Christ, freely offered to us in the gospel.", proofTexts: ['Acts 2:37', 'Acts 26:18', 'Ezekiel 36:26-27', 'John 6:44-45'] },
    { id: 'wsc-32', number: 32, category: 'Salvation', question: "What benefits do they that are effectually called partake of in this life?", answer: "They that are effectually called do in this life partake of justification, adoption, and sanctification, and the several benefits which in this life do either accompany or flow from them.", proofTexts: ['Romans 8:30', 'Ephesians 1:5', '1 Corinthians 1:30'] },
    { id: 'wsc-33', number: 33, category: 'Salvation', question: "What is justification?", answer: "Justification is an act of God's free grace, wherein he pardons all our sins, and accepts us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone.", proofTexts: ['Romans 3:24', '2 Corinthians 5:19', 'Romans 4:6-8', 'Philippians 3:9'] },
    { id: 'wsc-34', number: 34, category: 'Salvation', question: "What is adoption?", answer: "Adoption is an act of God's free grace, whereby we are received into the number, and have a right to all the privileges of, the sons of God.", proofTexts: ['1 John 3:1', 'John 1:12', 'Romans 8:17'] },
    { id: 'wsc-35', number: 35, category: 'Salvation', question: "What is sanctification?", answer: "Sanctification is the work of God's free grace, whereby we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness.", proofTexts: ['2 Thessalonians 2:13', 'Ephesians 4:23-24', 'Romans 6:4', 'Romans 8:1'] },
    { id: 'wsc-36', number: 36, category: 'Salvation', question: "What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?", answer: "The benefits which in this life do accompany or flow from justification, adoption, and sanctification, are, assurance of God's love, peace of conscience, joy in the Holy Ghost, increase of grace, and perseverance therein to the end.", proofTexts: ['Romans 5:1-5', 'Proverbs 4:18', '1 John 5:13'] },
    { id: 'wsc-37', number: 37, category: 'Salvation', question: "What benefits do believers receive from Christ at death?", answer: "The souls of believers are at their death made perfect in holiness, and do immediately pass into glory; and their bodies, being still united to Christ, do rest in their graves till the resurrection.", proofTexts: ['Hebrews 12:23', 'Philippians 1:23', '1 Thessalonians 4:14'] },
    { id: 'wsc-38', number: 38, category: 'Salvation', question: "What benefits do believers receive from Christ at the resurrection?", answer: "At the resurrection, believers being raised up in glory, shall be publicly acknowledged and acquitted in the day of judgment, and made perfectly blessed in the full enjoying of God to all eternity.", proofTexts: ['1 Corinthians 15:43', 'Matthew 10:32', '1 Thessalonians 4:17'] },
    { id: 'wsc-39', number: 39, category: 'Law', question: "What is the duty which God requires of man?", answer: "The duty which God requires of man, is obedience to his revealed will.", proofTexts: ['Micah 6:8', '1 Samuel 15:22'] },
    { id: 'wsc-40', number: 40, category: 'Law', question: "What did God at first reveal to man for the rule of his obedience?", answer: "The rule which God at first revealed to man for his obedience, was the moral law.", proofTexts: ['Romans 2:14-15', 'Romans 10:5'] },
    { id: 'wsc-41', number: 41, category: 'Law', question: "Where is the moral law summarily comprehended?", answer: "The moral law is summarily comprehended in the ten commandments.", proofTexts: ['Deuteronomy 10:4', 'Matthew 19:17-19'] },
    { id: 'wsc-42', number: 42, category: 'Law', question: "What is the sum of the ten commandments?", answer: "The sum of the ten commandments is, to love the Lord our God with all our heart, with all our soul, with all our strength, and with all our mind; and our neighbor as ourselves.", proofTexts: ['Matthew 22:37-40'] },
    { id: 'wsc-85', number: 85, category: 'Sacraments', question: "What does God require of us, that we may escape his wrath and curse due to us for sin?", answer: "To escape the wrath and curse of God due to us for sin, God requires of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means whereby Christ communicates to us the benefits of redemption.", proofTexts: ['Acts 20:21', '2 Peter 1:10', 'Proverbs 8:34-35'] },
    { id: 'wsc-86', number: 86, category: 'Law', question: "What is faith in Jesus Christ?", answer: "Faith in Jesus Christ is a saving grace, whereby we receive and rest upon him alone for salvation, as he is offered to us in the gospel.", proofTexts: ['Hebrews 10:39', 'John 1:12', 'Philippians 3:9'] },
    { id: 'wsc-87', number: 87, category: 'Law', question: "What is repentance unto life?", answer: "Repentance unto life is a saving grace, whereby a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, does, with grief and hatred of his sin, turn from it unto God, with full purpose of, and endeavor after, new obedience.", proofTexts: ['Acts 2:37-38', 'Joel 2:12-13', 'Jeremiah 31:18-19', 'Luke 1:6'] },
    { id: 'wsc-88', number: 88, category: 'Sacraments', question: "What are the outward and ordinary means whereby Christ communicates to us the benefits of redemption?", answer: "The outward and ordinary means whereby Christ communicates to us the benefits of redemption are, his ordinances, especially the Word, sacraments, and prayer; all which are made effectual to the elect for salvation.", proofTexts: ['Matthew 28:19-20', 'Acts 2:41-42'] },
    { id: 'wsc-98', number: 98, category: 'Prayer', question: "What is prayer?", answer: "Prayer is an offering up of our desires unto God, for things agreeable to his will, in the name of Christ, with confession of our sins, and thankful acknowledgement of his mercies.", proofTexts: ['Psalm 62:8', '1 John 5:14', 'John 16:23', 'Psalm 32:5-6', 'Philippians 4:6'] },
    { id: 'wsc-99', number: 99, category: 'Prayer', question: "What rule has God given for our direction in prayer?", answer: "The whole Word of God is of use to direct us in prayer; but the special rule of direction is that form of prayer which Christ taught his disciples, commonly called The Lord's Prayer.", proofTexts: ['1 John 5:14', 'Matthew 6:9-13'] },
    { id: 'wsc-107', number: 107, category: 'Prayer', question: "What does the conclusion of the Lord's prayer teach us?", answer: "The conclusion of the Lord's prayer (which is, 'For thine is the kingdom, and the power, and the glory, forever, Amen') teaches us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power, and glory to him; and, in testimony of our desire, and assurance to be heard, we say, Amen.", proofTexts: ['Romans 11:36', '1 Chronicles 29:11-13', '1 Corinthians 14:16', 'Revelation 22:20'] },
  ],
};

export const HEIDELBERG: Catechism = {
  id: 'hc',
  name: 'Heidelberg Catechism',
  shortName: 'HC',
  year: '1563',
  tradition: 'Reformed / Continental',
  description: 'Written in Heidelberg under Elector Frederick III, this catechism is beloved for its warm, personal tone and its organization around comfort, guilt, and grace.',
  questions: [
    { id: 'hc-1', number: 1, category: 'Comfort', question: "What is your only comfort in life and death?", answer: "That I am not my own, but belong—body and soul, in life and in death—to my faithful Savior, Jesus Christ. He has fully paid for all my sins with his precious blood, and has set me free from the tyranny of the devil. He also watches over me in such a way that not a hair can fall from my head without the will of my Father in heaven; in fact, all things must work together for my salvation. Because I belong to him, Christ, by his Holy Spirit, assures me of eternal life and makes me wholeheartedly willing and ready from now on to live for him.", proofTexts: ['1 Corinthians 6:19-20', 'Romans 8:28', 'John 10:27-30', 'Romans 8:38-39'] },
    { id: 'hc-2', number: 2, category: 'Comfort', question: "What must you know to live and die in the joy of this comfort?", answer: "Three things: first, how great my sin and misery are; second, how I am set free from all my sins and their misery; third, how I am to thank God for such deliverance.", proofTexts: ['Romans 3:10', 'John 17:3', 'Ephesians 5:20', 'Matthew 5:16'] },
    { id: 'hc-3', number: 3, category: 'Sin', question: "How do you come to know your misery?", answer: "The law of God tells me.", proofTexts: ['Romans 3:20', 'Romans 7:7-25'] },
    { id: 'hc-4', number: 4, category: 'Sin', question: "What does God's law require of us?", answer: "Christ teaches us this in summary in Matthew 22: 'Love the Lord your God with all your heart and with all your soul and with all your mind and with all your strength. This is the first and greatest commandment. And the second is like it: Love your neighbor as yourself. All the Law and the Prophets hang on these two commandments.'", proofTexts: ['Matthew 22:37-40', 'Luke 10:27', 'Deuteronomy 6:5'] },
    { id: 'hc-5', number: 5, category: 'Sin', question: "Can you live up to all this perfectly?", answer: "No. I have a natural tendency to hate God and my neighbor.", proofTexts: ['Romans 3:9-20', 'Romans 7:23', 'Titus 3:3', '1 John 1:8'] },
    { id: 'hc-12', number: 12, category: 'Redemption', question: "According to God's righteous judgment we deserve punishment both in this world and forever after: how then can we escape this punishment and return to God's favor?", answer: "God requires that his justice be satisfied. Therefore the claims of his justice must be paid in full, either by ourselves or another.", proofTexts: ['Exodus 20:5', 'Hebrews 9:22', 'Romans 8:3-4'] },
    { id: 'hc-26', number: 26, category: 'God', question: "What do you believe when you say: 'I believe in God, the Father almighty, creator of heaven and earth'?", answer: "That the eternal Father of our Lord Jesus Christ, who out of nothing created heaven and earth and everything in them, who still upholds and rules them by his eternal counsel and providence, is my God and Father because of Christ the Son. I trust him so much that I do not doubt he will provide whatever I need for body and soul, and he will turn to my good whatever adversity he sends me in this sad world. He is able to do this because he is almighty God; he desires to do this because he is a faithful Father.", proofTexts: ['Genesis 1:1', 'John 1:3', 'Hebrews 1:3', 'Romans 8:15-16', 'Matthew 10:29-31'] },
    { id: 'hc-27', number: 27, category: 'Providence', question: "What do you understand by the providence of God?", answer: "Providence is the almighty and ever present power of God by which he upholds, as with his hand, heaven and earth and all creatures, and so rules them that leaf and blade, rain and drought, fruitful and lean years, food and drink, health and sickness, prosperity and poverty—all things, in fact, come to us not by chance but from his fatherly hand.", proofTexts: ['Psalm 104:27-30', 'Acts 17:25-28', 'Jeremiah 5:24', 'Proverbs 22:2'] },
    { id: 'hc-59', number: 59, category: 'Salvation', question: "What good does it do you, however, to believe all this?", answer: "In Christ I am right with God and heir to life everlasting.", proofTexts: ['Romans 1:17', 'John 17:3'] },
    { id: 'hc-60', number: 60, category: 'Salvation', question: "How are you right with God?", answer: "Only by true faith in Jesus Christ. Even though my conscience accuses me of having grievously sinned against all God's commandments and of never having kept any of them, and even though I am still inclined toward all evil, nevertheless, without my deserving it at all, out of sheer grace, God grants and credits to me the perfect satisfaction, righteousness, and holiness of Christ, as if I had never sinned nor been a sinner, as if I had been as perfectly obedient as Christ was obedient for me. All I need to do is to accept this gift of God with a believing heart.", proofTexts: ['Romans 3:21-25', 'Galatians 2:16', '2 Corinthians 5:17-19', 'Romans 4:4-5'] },
    { id: 'hc-86', number: 86, category: 'Obedience', question: "Since we have been delivered from our misery by grace through Christ without any merit of our own, why then should we do good works?", answer: "Because Christ, having redeemed and delivered us by his blood, is also restoring us by his Spirit into his image; so that with our whole lives we may show that we are thankful to God for his benefits, so that he may be praised through us, so that we may be assured of our faith by its fruits, and so that by our godly living our neighbors may be won over to Christ.", proofTexts: ['Romans 6:13', 'Matthew 5:16', '2 Peter 1:10', '1 Peter 2:12'] },
    { id: 'hc-116', number: 116, category: 'Prayer', question: "Why do Christians need to pray?", answer: "Because prayer is the most important part of the thankfulness God requires of us. And also because God gives his grace and Holy Spirit only to those who pray continually and groan inwardly, asking God for these gifts and thanking him for them.", proofTexts: ['Psalm 50:14-15', 'Matthew 7:7-8', 'Luke 11:9-13'] },
    { id: 'hc-129', number: 129, category: 'Prayer', question: "What does that little word 'Amen' express?", answer: "'Amen' means: this is sure to be! It is even more sure that God listens to my prayer than that I really desire what I pray for.", proofTexts: ['2 Corinthians 1:20', 'Revelation 22:20-21'] },
  ],
};

export const ALL_CATECHISMS: Catechism[] = [WESTMINSTER_SHORTER, HEIDELBERG];

export const CATEGORIES = (catechism: Catechism): string[] =>
  [...new Set(catechism.questions.map(q => q.category))];
