import styles from './ProvenanceBadge.module.css';

export type ProvenanceVariant = 'dictionary' | 'curated' | 'ai' | 'sample';

const META: Record<ProvenanceVariant, { label: string; hint: string }> = {
  dictionary: {
    label: 'Dictionary',
    hint: 'Sourced from the bundled Strong\u2019s dictionaries / Treasury of Scripture Knowledge (offline data \u2014 no AI involved).',
  },
  curated: {
    label: 'Curated',
    hint: 'Hand-picked content bundled with BibleDesk (not AI-generated).',
  },
  ai: {
    label: 'AI',
    hint: 'Generated by AI. May contain errors \u2014 verify against Scripture.',
  },
  sample: {
    label: 'Sample',
    hint: 'Demo/seed data shipped for illustration.',
  },
};

interface ProvenanceBadgeProps {
  variant: ProvenanceVariant;
}

/**
 * Labels where a content block came from. Every Strong's card, cross-reference
 * block, and AI panel in the reader must carry one of these.
 */
export default function ProvenanceBadge({ variant }: ProvenanceBadgeProps) {
  const meta = META[variant];
  return (
    <span className={`${styles.badge} ${styles[variant]}`} title={meta.hint}>
      <span className={styles.dot} aria-hidden="true" />
      {meta.label}
    </span>
  );
}
